### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by berthelemy** [h5p/h5p-exportable-text-area#1]
Hi there,

When I try to export text nothing happens on screen and the following error is reported in the console:

Uncaught TypeError: Cannot read property 'length' of undefined
H5P.ExportableTextArea.Exporter.createDocContent @ eta.js?ver=1.1.0:133
H5P.ExportableTextArea.Exporter.run @ eta.js?ver=1.1.0:120
(anonymous function) @ summary-slide.js?ver=1.3.3:87
b.event.dispatch @ jquery.js?ver=1.5.0:2
v.handle @ jquery.js?ver=1.5.0:2

I'm using Chrome 42 on Mac OS 10.10.2

Thanks,

Mark

**Comment by icc** [comment]
Hi! It seems you're running an old version of the presentation tool. Here's a short tutorial on how you can upgrade to the latest version:
http://h5p.org/update-all-content-types

**Comment by berthelemy** [comment]
Thanks Frode,

That worked. It turns out I was using the now-deprecated version of the
presentation tool.

Is there any way to migrate old presentations to the new version?

Cheers,

Mark

On 24 April 2015 at 08:38, Frode Petterson <notifications@github.com> wrote:

> Hi! It seems you're running an old version of the presentation tool.
> Here's a short tutorial on how you can upgrade to the latest version:
> http://h5p.org/update-all-content-types
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/h5p/h5p-exportable-text-area/issues/1#issuecomment-95835720>
> .
>



-- 

Mark Berthelemy
Managing Director
Tel: 01773 881 227
Mob: 07922 146 761

Web: www.wyversolutions.co.uk

Wyver Solutions Ltd | Company number: 5731173 Registered in England |
Registered address: First Floor, 6 Bridge Street, Belper, Derbyshire, DE56
1AX

**Comment by icc** [comment]
Yes, you should be able to press the little green arrow next to the library on the libraries page. Here you can choose which version you wish to upgrade the content to.

**Comment by berthelemy** [comment]
Perfect!

Thanks :-)

On 24 April 2015 at 09:25, Frode Petterson <notifications@github.com> wrote:

> Yes, you should be able to press the little green arrow next to the
> library on the libraries page. Here you can choose which version you wish
> to upgrade the content to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/h5p/h5p-exportable-text-area/issues/1#issuecomment-95851361>
> .
>



-- 

Mark Berthelemy
Managing Director
Tel: 01773 881 227
Mob: 07922 146 761

Web: www.wyversolutions.co.uk

Wyver Solutions Ltd | Company number: 5731173 Registered in England |
Registered address: First Floor, 6 Bridge Street, Belper, Derbyshire, DE56
1AX
